### ISSUE TITLE
Error in "Exercise 3.3.pdf"

### ISSUE THREAD

**Issue by jagandecapri** [matrixbud/Quantum-Mechanics---The-Theoretical-Minimum#1]
Hi @matrixbud ,

I think there is an error in https://github.com/matrixbud/Quantum-Mechanics---The-Theoretical-Minimum/blob/dd9c5211990557e123794d4e4a22d4a78176ac26/Exercise%203.3.pdf as below:

<img width="608" alt="2019-10-29 22_20_50-Quantum-Mechanics---The-Theoretical-Minimum_Exercise 3 3 pdf at master · matrixb" src="https://user-images.githubusercontent.com/5851344/67776389-348c5e00-fa9b-11e9-83a8-4b803a62693d.png">

It should be <img src="https://render.githubusercontent.com/render/math?math=\begin{bmatrix}-sin(\Theta/2)\\ cos(\Theta/2)\\\end{bmatrix}"> I suppose.

**Comment by matrixbud** [comment]
Yep. Thanks! Let me know of any other things you find, also. I didn’t check any of my work with anyone else.


Bud Simrin
uvw@sbcglobal.net

**Comment by jagandecapri** [comment]
Sure. No problem. 👍 

Regards,
Jack
