### ISSUE TITLE
Error in "Exercise 3.4.pdf"

### ISSUE THREAD

**Issue by jagandecapri** [matrixbud/Quantum-Mechanics---The-Theoretical-Minimum#2]
Hi @matrixbud,

I think there is an error in https://github.com/matrixbud/Quantum-Mechanics---The-Theoretical-Minimum/blob/6a2a2a1cc3b2db623ec5c208cd9117f2b85783ae/Exercise%203.4.pdf as below:

![2019-11-03 22_28_46-Quantum-Mechanics---The-Theoretical-Minimum_Exercise 3 4 pdf at master · matrixb](https://user-images.githubusercontent.com/5851344/68086820-9d544b80-fe8a-11e9-8295-cc9d31be2fc3.png)

It should be <img src="https://render.githubusercontent.com/render/math?math=\lambda_{2}"></img> I suppose.

Btw, thank you for the notes and answers. It's helping me a lot in my self-learning journey. :)

**Comment by matrixbud** [comment]
Right you are. I’ll make the change. 

It’s nice to get feedback that someone actually looks at these postings. I hope I don’t lead you down any wrong paths.


Bud Simrin
uvw@sbcglobal.net

**Comment by jagandecapri** [comment]
No worries. Thank you!
